vim.g.mapleader = " "
vim.keymap.set("n", "<leader>e", vim.cmd.Ex)
vim.keymap.set("n", "<leader>p", vim.cmd.PackerSync)
vim.keymap.set("n", "<leader>cm", vim.cmd.Mason)
vim.keymap.set("n", "<leader>gg", vim.cmd.LazyGit)
vim.keymap.set("n", "<leader>bd", vim.cmd.bdelete)
vim.keymap.set("n", "<C-s>", vim.cmd.w)
vim.keymap.set("i", "<C-s>", vim.cmd.w, { noremap = true })
vim.keymap.set("n", "<leader>qq", vim.cmd.quit)
vim.keymap.set("n", "cd", "<cmd>lua vim.diagnostic.open_float()<CR>")
vim.keymap.set("n", "fd", "<cmd>Telescope diagnostics<CR>")
vim.keymap.set("n", "ca", "<cmd>lua vim.lsp.buf.code_action()<CR>")
vim.keymap.set("n", "cf", "<cmd>lua vim.lsp.buf.format()<CR>")
vim.keymap.set("n", "cr", "<cmd>lua vim.lsp.buf.rename()<CR>")
vim.keymap.set("n", "cs", "<cmd>lua vim.lsp.buf.signature_help()<CR>")
vim.keymap.set("n", "crf", "<cmd>lua vim.lsp.buf.references()<CR>")
vim.keymap.set("n", "ch", "<cmd>lua vim.lsp.buf.hover()<CR>")
vim.keymap.set("n", "gdf", "<cmd>lua vim.lsp.buf.definition()<CR>")
vim.keymap.set("n", "gd", "<cmd>lua vim.lsp.buf.declaration()<CR>")
vim.keymap.set("n", "ci", "<cmd>lua vim.lsp.buf.implementation()<CR>")
vim.keymap.set("n", "gtd", "<cmd>lua vim.lsp.buf.type_definition()<CR>")
vim.keymap.set("n", "<A-j>", "<cmd>m .+1<cr>==")
vim.keymap.set("n", "<A-k>", "<cmd>m .-2<cr>==")
vim.keymap.set("i", "<A-j>", "<esc><cmd>m .+1<cr>==gi")
vim.keymap.set("i", "<A-k>", "<esc><cmd>m .-2<cr>==gi")
vim.keymap.set("v", "<A-j>", ":m '>+1<cr>gv=gv")
vim.keymap.set("v", "<A-k>", ":m '<-2<cr>gv=gv")
